/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'navy-primary': '#1B2B4B',
        'accent-gold': '#C9A84C',
        'teal-accent': '#1A6B6B',
        'bg-light': '#F4F6F9',
        'surface-white': '#FFFFFF',
        'border-subtle': '#D0D7E3',
        'text-dark': '#1E1E2E',
        'text-muted': '#5A5F72',
        'success-green': '#16A34A',
        'warning-amber': '#D97706',
        'error-red': '#DC2626',
        // New Google Stitch Colors
        "surface-container-low": "#eef4ff",
        "outline-variant": "#c5c6cf",
        "tertiary-container": "#003232",
        "background": "#f8f9ff",
        "inverse-primary": "#b7c6ee",
        "on-tertiary-fixed": "#002020",
        "on-surface": "#151c25",
        "surface-container-high": "#e2e9f5",
        "tertiary": "#001b1b",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#e6c364",
        "secondary-fixed": "#ffe08f",
        "on-primary-fixed-variant": "#374668",
        "on-primary-fixed": "#091b3a",
        "surface": "#f8f9ff",
        "outline": "#75777f",
        "surface-tint": "#4f5e81",
        "primary-fixed-dim": "#b7c6ee",
        "surface-bright": "#f8f9ff",
        "secondary-container": "#fed977",
        "surface-container": "#e7eefb",
        "on-primary-container": "#8393b8",
        "inverse-on-surface": "#eaf1fd",
        "on-secondary-container": "#785d00",
        "primary-container": "#1b2b4b",
        "on-secondary-fixed-variant": "#584400",
        "on-surface-variant": "#44474e",
        "on-background": "#151c25",
        "on-tertiary-container": "#569f9f",
        "secondary": "#755b00",
        "tertiary-fixed": "#a6efef",
        "inverse-surface": "#2a313a",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#dce3ef",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#241a00",
        "tertiary-fixed-dim": "#8bd3d2",
        "surface-variant": "#dce3ef",
        "on-error": "#ffffff",
        "primary-fixed": "#d8e2ff",
        "error": "#ba1a1a",
        "surface-dim": "#d3dae6",
        "on-secondary": "#ffffff",
        "primary": "#041635",
        "on-tertiary-fixed-variant": "#004f50"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "gap-grid": "1rem",
        "container-max": "1280px",
        "padding-card": "1.5rem",
        "section-margin": "2rem",
        "xs": "4px",
        "sm": "12px",
        "md": "24px",
        "lg": "40px",
        "xl": "64px",
        "gutter": "24px"
      },
      fontFamily: {
        serif: ['"Source Serif 4"', 'Georgia', 'serif'],
        sans: ['"Work Sans"', 'Inter', 'system-ui', 'sans-serif'],
        "display-lg": ["\"Source Serif 4\""],
        "label-md": ["Work Sans", "Inter"],
        "headline-md": ["\"Source Serif 4\""],
        "headline-sm": ["Work Sans", "Inter"],
        "body-md": ["Work Sans", "Inter"],
        "body-sm": ["Work Sans", "Inter"],
        "display-lg-mobile": ["\"Source Serif 4\""],
        "body-lg": ["Inter"],
        "label-sm": ["Inter"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"]
      },
      fontSize: {
        "display-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "label-md": ["13px", {"lineHeight": "1", "letterSpacing": "0.02em", "fontWeight": "500"}],
        "headline-md": ["22px", {"lineHeight": "1.3", "fontWeight": "700"}],
        "headline-sm": ["18px", {"lineHeight": "1.4", "fontWeight": "600"}],
        "body-md": ["15px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "display-lg-mobile": ["28px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
        "label-sm": ["12px", {"lineHeight": "16px", "fontWeight": "500"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600"}]
      },
      animation: {
        'in': 'fadeIn 0.3s ease-in-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0', transform: 'translateY(10px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
}
