// Canonical contracts.status values — mirrors the CHECK constraint added in
// sql/73_contract_status_normalization.sql. Import from here instead of
// comparing against string literals.
export const CONTRACT_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_ACCEPTANCE: 'PENDING_ACCEPTANCE',
  ACCEPTED: 'ACCEPTED',
  ACTIVE: 'ACTIVE',
  MILESTONE_IN_PROGRESS: 'MILESTONE_IN_PROGRESS',
  MILESTONE_COMPLETED: 'MILESTONE_COMPLETED',
  DELIVERY_SUBMITTED: 'DELIVERY_SUBMITTED',
  UNDER_CLIENT_REVIEW: 'UNDER_CLIENT_REVIEW',
  REVISION_REQUESTED: 'REVISION_REQUESTED',
  APPROVED: 'APPROVED',
  COMPLETION_REQUESTED: 'COMPLETION_REQUESTED',
  COMPLETED: 'COMPLETED',
  REVIEW_PENDING: 'REVIEW_PENDING',
  REVIEWED: 'REVIEWED',
  CLOSED: 'CLOSED',
  TERMINATED: 'TERMINATED',
  ARCHIVED: 'ARCHIVED',
};

// Human-readable labels — raw canonical values like REVIEW_PENDING should
// never be rendered directly to users.
export const CONTRACT_STATUS_LABELS = {
  [CONTRACT_STATUS.DRAFT]: 'Draft',
  [CONTRACT_STATUS.PENDING_ACCEPTANCE]: 'Awaiting Your Acceptance',
  [CONTRACT_STATUS.ACCEPTED]: 'Accepted',
  [CONTRACT_STATUS.ACTIVE]: 'Active',
  [CONTRACT_STATUS.MILESTONE_IN_PROGRESS]: 'Milestone In Progress',
  [CONTRACT_STATUS.MILESTONE_COMPLETED]: 'Milestone Completed',
  [CONTRACT_STATUS.DELIVERY_SUBMITTED]: 'Delivery Submitted',
  [CONTRACT_STATUS.UNDER_CLIENT_REVIEW]: 'Under Client Review',
  [CONTRACT_STATUS.REVISION_REQUESTED]: 'Revision Requested',
  [CONTRACT_STATUS.APPROVED]: 'Approved',
  [CONTRACT_STATUS.COMPLETION_REQUESTED]: 'Awaiting Client Approval',
  [CONTRACT_STATUS.COMPLETED]: 'Completed',
  [CONTRACT_STATUS.REVIEW_PENDING]: 'Completed — Review Pending',
  [CONTRACT_STATUS.REVIEWED]: 'Completed — Reviewed',
  [CONTRACT_STATUS.CLOSED]: 'Closed',
  [CONTRACT_STATUS.TERMINATED]: 'Terminated',
  [CONTRACT_STATUS.ARCHIVED]: 'Archived',
};

export const contractStatusLabel = (status) =>
  CONTRACT_STATUS_LABELS[status] || String(status || '').replace(/_/g, ' ');

const ACTIVE_STATUSES = new Set([
  CONTRACT_STATUS.PENDING_ACCEPTANCE,
  CONTRACT_STATUS.ACCEPTED,
  CONTRACT_STATUS.ACTIVE,
  CONTRACT_STATUS.MILESTONE_IN_PROGRESS,
  CONTRACT_STATUS.MILESTONE_COMPLETED,
  CONTRACT_STATUS.DELIVERY_SUBMITTED,
  CONTRACT_STATUS.UNDER_CLIENT_REVIEW,
  CONTRACT_STATUS.REVISION_REQUESTED,
  CONTRACT_STATUS.APPROVED,
  CONTRACT_STATUS.COMPLETION_REQUESTED,
]);

const TERMINAL_STATUSES = new Set([
  CONTRACT_STATUS.COMPLETED,
  CONTRACT_STATUS.REVIEW_PENDING,
  CONTRACT_STATUS.REVIEWED,
  CONTRACT_STATUS.CLOSED,
  CONTRACT_STATUS.TERMINATED,
  CONTRACT_STATUS.ARCHIVED,
]);

export const isActiveStatus = (status) => ACTIVE_STATUSES.has(status);
export const isTerminalStatus = (status) => TERMINAL_STATUSES.has(status);
export const isRevisionRequested = (status) => status === CONTRACT_STATUS.REVISION_REQUESTED;
export const isUnderClientReview = (status) => status === CONTRACT_STATUS.UNDER_CLIENT_REVIEW;
