// Canonical contracts.status values — mirrors the CHECK constraint added in
// sql/73_contract_status_normalization.sql. Import from here instead of
// comparing against string literals.
export const CONTRACT_STATUS = {
  DRAFT: 'DRAFT',
  PENDING_ACCEPTANCE: 'PENDING_ACCEPTANCE',
  ACCEPTED: 'ACCEPTED',
  ACTIVE: 'ACTIVE',
  MILESTONE_IN_PROGRESS: 'MILESTONE_IN_PROGRESS',
  MILESTONE_COMPLETED: 'MILESTONE_COMPLETED',
  DELIVERY_SUBMITTED: 'DELIVERY_SUBMITTED',
  UNDER_CLIENT_REVIEW: 'UNDER_CLIENT_REVIEW',
  REVISION_REQUESTED: 'REVISION_REQUESTED',
  APPROVED: 'APPROVED',
  COMPLETED: 'COMPLETED',
  REVIEW_PENDING: 'REVIEW_PENDING',
  REVIEWED: 'REVIEWED',
  CLOSED: 'CLOSED',
  TERMINATED: 'TERMINATED',
  ARCHIVED: 'ARCHIVED',
};

const ACTIVE_STATUSES = new Set([
  CONTRACT_STATUS.PENDING_ACCEPTANCE,
  CONTRACT_STATUS.ACCEPTED,
  CONTRACT_STATUS.ACTIVE,
  CONTRACT_STATUS.MILESTONE_IN_PROGRESS,
  CONTRACT_STATUS.MILESTONE_COMPLETED,
  CONTRACT_STATUS.DELIVERY_SUBMITTED,
  CONTRACT_STATUS.UNDER_CLIENT_REVIEW,
  CONTRACT_STATUS.REVISION_REQUESTED,
  CONTRACT_STATUS.APPROVED,
]);

const TERMINAL_STATUSES = new Set([
  CONTRACT_STATUS.COMPLETED,
  CONTRACT_STATUS.REVIEW_PENDING,
  CONTRACT_STATUS.REVIEWED,
  CONTRACT_STATUS.CLOSED,
  CONTRACT_STATUS.TERMINATED,
  CONTRACT_STATUS.ARCHIVED,
]);

export const isActiveStatus = (status) => ACTIVE_STATUSES.has(status);
export const isTerminalStatus = (status) => TERMINAL_STATUSES.has(status);
export const isRevisionRequested = (status) => status === CONTRACT_STATUS.REVISION_REQUESTED;
export const isUnderClientReview = (status) => status === CONTRACT_STATUS.UNDER_CLIENT_REVIEW;
